// src/modules/notifications/domain/enums/notification-type.enum.ts
export enum NotificationType {
  // Task notifications
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_COMMENT_ADDED = 'TASK_COMMENT_ADDED',
  TASK_DUE_SOON = 'TASK_DUE_SOON',
  TASK_OVERDUE = 'TASK_OVERDUE',

  // Meeting notifications
  MEETING_INVITATION = 'MEETING_INVITATION',
  MEETING_UPDATED = 'MEETING_UPDATED',
  MEETING_CANCELLED = 'MEETING_CANCELLED',
  MEETING_REMINDER = 'MEETING_REMINDER',
  MEETING_STARTING_SOON = 'MEETING_STARTING_SOON',
  MEETING_RESPONSE_NEEDED = 'MEETING_RESPONSE_NEEDED',

  // User notifications
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ACCOUNT_UPDATED = 'ACCOUNT_UPDATED',

  // Digest notifications
  DAILY_DIGEST = 'DAILY_DIGEST',
  WEEKLY_DIGEST = 'WEEKLY_DIGEST',
}
