export enum ActivityType {
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_CREATED = 'TASK_CREATED',
  CLUB_MEMBER_JOINED = 'CLUB_MEMBER_JOINED',
  MEETING_SCHEDULED = 'MEETING_SCHEDULED',
  MEETING_CANCELLED = 'MEETING_CANCELLED',
  USER_JOINED = 'USER_JOINED',
  SOCIAL_POST_CREATED = 'SOCIAL_POST_CREATED',
  SOCIAL_POST_LIKED = 'SOCIAL_POST_LIKED',
  SOCIAL_COMMENT_ADDED = 'SOCIAL_COMMENT_ADDED',
}
