export enum ModerationAction {
  WARN = 'WARN',
  HIDE_CONTENT = 'HIDE_CONTENT',
  DELETE_CONTENT = 'DELETE_CONTENT',
  SUSPEND_USER = 'SUSPEND_USER',
  BAN_USER_PERMANENT = 'BAN_USER_PERMANENT',
  BAN_USER_TEMPORARY = 'BAN_USER_TEMPORARY',
  RESTORE_CONTENT = 'RESTORE_CONTENT',
}
