export enum ReportReason {
  HARASSMENT = 'HARASSMENT',
  HATE_SPEECH = 'HATE_SPEECH',
  SPAM = 'SPAM',
  MISINFORMATION = 'MISINFORMATION',
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  COPYRIGHT = 'COPYRIGHT',
  VIOLENCE = 'VIOLENCE',
  OTHER = 'OTHER',
}
