export enum ActivityAction {
  CREATED = 'CREATED',
  STATUS_UPDATED = 'STATUS_UPDATED',
  ASSIGNED = 'ASSIGNED',
  VISIBILITY_UPDATED = 'VISIBILITY_UPDATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  SUBTASK_ADDED = 'SUBTASK_ADDED',
  SUBTASK_UPDATED = 'SUBTASK_UPDATED',
  TAG_ADDED = 'TAG_ADDED',
  TAG_REMOVED = 'TAG_REMOVED',
}
