export enum BadgeType {
  TASK_COMPLETED = 'TASK_COMPLETED',
  FIRST_TASK = 'FIRST_TASK',
  TASKS_STREAK = 'TASKS_STREAK',
  MENTOR = 'MENTOR',
  HELPER = 'HELPER',
  QUICK_RESPONDER = 'QUICK_RESPONDER',
  HIGH_QUALITY = 'HIGH_QUALITY',
  COMMUNITY_CONTRIBUTOR = 'COMMUNITY_CONTRIBUTOR',
}
